### PR TITLE
Second go...

### PR DESCRIPTION
**Pull request by PhotonQyv**
Put a UNIQUE constraint on the two columns instance, and status_id, so that in combination they have to be unique.

### CODE REVIEW

**Comment by stom79** [comment]
@PhotonQyv Could you test this on your device and see if there is no issue even with the duplicate entry?

**Comment by PhotonQyv** [comment]
@stom79 Running the altered table in the db on this tablet, imported all my toots, from all my Mastodon accounts, no duplicates, no issues with it. You just need to make sure that upgrade method gets called to drop the old table and create the newer one. Sqlite won't allow you to add constraints to an existing table, unfortunately.

**Comment by stom79** [comment]
Ah OK. So my upgrade uses "alter table"  to add this constraint for people who already have the app installed. I thought it would be OK. I will remove my "alter table"  and add a "drop / create". That means people will lose their cache.

**Comment by PhotonQyv** [comment]
@stom79 The other way to do it might be to use the following syntax:

CREATE UNIQUE INDEX instance_statusid on STATUSES_CACHE(INSTANCE, STATUS_ID);

cf. [SQLite 'ALTER TABLE'](https://stackoverflow.com/questions/9843229/sqlitealter-table-game-add-uniquename-error-in-sqlite?rq=1)

That way you don't lose the cached toots.

**Comment by stom79** [comment]
Thanks! I will do that or could you change my piece of code?

**Comment by PhotonQyv** [comment]
@stom79 I'll take a look (:*

**Comment by PhotonQyv** [comment]
@stom79 Think that's got it. Added another string for the CREATE INDEX, and added sqlExecute() for it to onCreate() and onUpgrade() methods.

**Comment by PhotonQyv** [comment]
@stom79 Just merged it with my version, and building now.

**Pull request merged**
