### PR TITLE
Fixing Dutch

### PR DESCRIPTION
**Pull request by jeroenpraat**
There were some strings reverted by accident. Fixed it and also fixed a typo I made.

### CODE REVIEW

**Comment by stom79** [comment]
Thanks! And sorry for this mistake. I don't know how it happened. I hope crowdin is not related to that issue because PR are done automatically. Or could you use Crowdin?

**Comment by jeroenpraat** [comment]
No problem. And no I just do it by hand.

**Comment by stom79** [comment]
OK. This is clearly crowdin which overrides your work. As an example, I got this automatic PR and the translations are gone again: https://github.com/stom79/mastalab/pull/147/commits/ed0a05a31b2f0f663fad24897d3a819c6989bbb7

**Comment by jeroenpraat** [comment]
How do we avoid this?

**Comment by stom79** [comment]
There are two solutions:
- Use crowdin
or
- PR on l10n_crowdin_localization branch

I will investigate about this issue too.

**Comment by jeroenpraat** [comment]
If you like me to use Crowdin, it's ok for me. I also use Transifex and Weblate, so another translation tool wouldn't blow my mind ;-).

**Pull request merged**
